- xdrip.xcodeproj/project.pbxproj
- xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralType.swift
- xdrip/BluetoothTransmitter/CGM/Dexcom/G4/CGMG4xDripTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Dexcom/G5/CGMG5Transmitter.swift
- xdrip/BluetoothTransmitter/CGM/Generic/CGMTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Blucon/CGMBluconTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/BlueReader/CGMBlueReaderTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Droplet/CGMDroplet1Transmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/GNSEntry/CGMGNSEntryTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/MiaoMiao/CGMMiaoMiaoTransmitter.swift
- xdrip/BluetoothTransmitter/watlaa/WatlaaBluetoothTransmitter.swift
- xdrip/BluetoothTransmitter/watlaa/WatlaaBluetoothTransmitterMaster+CGMTransmitter.swift
- xdrip/Calibration/Libre1NonFixedSlopeCalibrator.swift
- xdrip/Constants/ConstantsLibre.swift
- xdrip/Core Data/classes/BLEPeripheral+CoreDataClass.swift
- xdrip/Core Data/classes/BLEPeripheral+CoreDataProperties.swift
- xdrip/Core Data/xdrip.xcdatamodeld/xdrip v11.xcdatamodel/contents
- xdrip/Managers/BluetoothPeripheral/BluetoothPeripheralManager.swift
- xdrip/Managers/BluetoothPeripheral/BluetoothPeripheralManaging.swift
- xdrip/Storyboards/en.lproj/SettingsViews.strings
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/BluetoothPeripheralsNavigationController/BluetoothPeripheralsViewController/BluetoothPeripheralViewController/BluetoothPeripheralViewController.swift
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- xdrip/xdrip.entitlements
Add an option in the transmitter menu to enable non-fixed calibration slopes for Libre sensors. The slope parameters are taken from Spike/xDrip+. Tested with MM2 + Libre 1, and simulated other transmitters by enabling and disabling canUseNonFixed/canWebOOP for the Miaomiao.
The transmitter menu will look like this for a Libre transmitter that doesn't support web oop (Blucon, Droplet, etc):
<br>
This is for a transmitter that supports both web oop and non fixed slopes (Miaomiao, Bubble):
> Add non-fixed calibration slopes for Libre transmitters

- xdrip/Constants/ConstantsGlucoseChart.swift
- xdrip/Extensions/UserDefaults.swift
- xdrip/Managers/Charts/GlucoseChartManager.swift
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewHomeScreenSettingsViewModel.swift
With coloured glucose points, the coloured objective lines are no longer needed and are distracting.
This change will remove the option and revert all users back to grey objective/threshold lines as per Nightscout web view.
> Remove coloured objectives lines

- xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralType.swift
Reorder list to put most-used options at the top. (L2, MM, Bubble, G6, G5 etc).
Rename **Libre 2** to **Libre 2 Direct** to make it clearer that it's being treated as a transmitter type instead of just a sensor type.
> Add Bubble Mini and update CGM Tx list order

- xdrip/Storyboards/Base.lproj/Main.storyboard
- xdrip/View Controllers/Root View Controller/RootViewController.swift
This is taken from the idea in #263 but implements a double tap gesture to reset the chart to the present date time. All labels and values are also updated.
> Double-tap to reset main chart

- xdrip/Extensions/UserDefaults.swift
- xdrip/Storyboards/Base.lproj/Main.storyboard
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewHelpSettingModel.swift
This will add a help icon to the main toolbar. Too many users are not aware that they can access the help files from the Settings menu. This will make it very clear.
For more advanced users, they can select to hide this icon permanently from the Settings -> Help menu. 
The actual removal is done safely during viewDidLoad() of the RVC so a restart is needed for the change to be effective (the user will be notified of this when toggling the UISwitch). As this will generally only be used once in the app lifetime, it's not a problem.
> implement toolbar help icon

- xdrip.xcodeproj/project.pbxproj
- xdrip/Core Data/accessors/TreatmentEntryAccessor.swift
- xdrip/Core Data/classes/TreatmentEntry+CoreDataClass.swift
- xdrip/Core Data/classes/TreatmentEntry+CoreDataProperties.swift
- xdrip/Core Data/xdrip.xcdatamodeld/xdrip v16.xcdatamodel/contents
- xdrip/Extensions/Date.swift
- xdrip/Extensions/Double.swift
- xdrip/Managers/NightScout/NightScoutUploadManager.swift
- xdrip/Storyboards/Base.lproj/Main.storyboard
- xdrip/Storyboards/ar.lproj/Treatments.strings
- xdrip/Storyboards/de.lproj/Treatments.strings
- xdrip/Storyboards/en.lproj/Treatments.strings
- xdrip/Storyboards/es.lproj/Treatments.strings
- xdrip/Storyboards/fi.lproj/Treatments.strings
- xdrip/Storyboards/fr.lproj/Treatments.strings
- xdrip/Storyboards/it.lproj/Treatments.strings
- xdrip/Storyboards/nl.lproj/Treatments.strings
- xdrip/Storyboards/pl-PL.lproj/Treatments.strings
- xdrip/Storyboards/pt.lproj/Treatments.strings
- xdrip/Storyboards/ru.lproj/Treatments.strings
- xdrip/Storyboards/sl.lproj/Treatments.strings
- xdrip/Storyboards/sv.lproj/Treatments.strings
- xdrip/Storyboards/zh.lproj/Treatments.strings
- xdrip/Texts/TextsTreatmentsView.swift
- xdrip/Treatments/TreatmentNSResponse.swift
- xdrip/View Controllers/Treatments/TreatmentsInsertViewController.swift
- xdrip/View Controllers/Treatments/TreatmentsViewController.swift
Features:
- When uploaded, treatments get their id assigned from Nightscout response.
- On sync action (cloud button), gets the latest treatments from NS.
- Treatments are only created at CoreData if they do not previously exist.
Missing:
- Button press is still required for sync.
- Deletes and updates are not sent to NS yet.
This pull includes two TODO annotations:
1. At NightScoutUploadManager getRequest: TODO: Check the HTTPURLResponse response code, unsure how to.
2. At TreatmentsViewController syncButtonTapped TODO: set optimal value for getLatestTreatmentsNSResponses count.
> Working Nightscout treatments synchronization.

- xdrip/Managers/NightScout/NightScoutUploadManager.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewNightScoutSettingsViewModel.swift
Just to avoid running credentials test(s) when the user enters/modifies the Nightscout URL but hasn't yet added an authentication method.
Also logic correction.
> Nightscout auth improvements

- xdrip/Managers/BluetoothPeripheral/BluetoothPeripheralManager.swift
- xdrip/Managers/NightScout/Endpoint+NightScout.swift
- xdrip/Managers/NightScout/NightScoutFollowManager.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewNightScoutSettingsViewModel.swift
GET request modified to use only count - this ensures compatibility with Nightscout sites populated by Tomato
API_SECRET and Token authentication for Follower mode. This allows read-only sites to work. (e.g. if AUTH_DEFAULT_ROLES = denied)
Add Observers to also trigger a fresh download attempt when API_SECRET or Token is modified in the Settings
> Nightscout Follower improvements

- xdrip/Utilities/Trace.swift
Lots of new info added to the trace file and formatting updated.
Example of new trace file output (appinfo.txt):
```
App name: xDrip4iO5
Version: 4.9.1
Build number: 4174 (28 January 2022)
App first installed on: 23 February 2021 at 14:41:08 CET
App last opened on: 9 February 2022 at 17:52:14 CET
===================================================
Nightscout: Enabled
URL: Present
API_SECRET: Missing
Token: Present
Transmitter type: Dexcom
App settings:
Mode: Master
Show help icon: true
Translate help: false
Show BG in notification: false
Notification interval: 0 minutes
Show BG in app badge: true
Allow chart rotation: true
Show statistics: true
Use standard range: true
Days to use for statistics calculations: 1
Selected chart width: 5.0
Show sensor countdown: false
Use alternative …
```
> Trace file appinfo.txt improvements

- xdrip.xcodeproj/project.pbxproj
- xdrip/Application Delegate/AppDelegate.swift
- xdrip/Managers/QuickActions/QuickActionsManager.swift
- xdrip/Storyboards/QuickActions.strings
- xdrip/Texts/TextsQuickActions.swift
- xdrip/View Controllers/Helpers/SettingsViewModelProtocol.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewController.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewSpeakSettingsViewModel.swift
First, thanks for the great project. This app is at the core of my diabetes care. 🙏 
I am using Speak Readings when exercising to not stress about going low. I've found it quite inconvenient to go scrolling the settings screen to find the setting as I'm doing it frequently.
This PR adds a quick action to quickly toggle Speak Readings setting from home screen
This adds a new `QuickActionsManager` object that is owned by `AppDelegate` and which responsibility is
- Handling user-triggered actions and updating the relevant setting
- Keeping Quick Actions up-to-date if the setting is changed from settings screen
`SettingsViewModel.storeSectionReloadClosure`
- `rowReloadClosure` didn't fit my needs as reloading the specific rows always crashes as the number of rows change when …
> Add Quick Action for access to Speak Readings setting

- xdrip/Extensions/UserDefaults.swift
- xdrip/Storyboards/Base.lproj/Main.storyboard
- xdrip/Storyboards/ar.lproj/SettingsViews.strings
- xdrip/Storyboards/da.lproj/SettingsViews.strings
- xdrip/Storyboards/de.lproj/SettingsViews.strings
- xdrip/Storyboards/en.lproj/SettingsViews.strings
- xdrip/Storyboards/en.lproj/Treatments.strings
- xdrip/Storyboards/es.lproj/SettingsViews.strings
- xdrip/Storyboards/es.lproj/Treatments.strings
- xdrip/Storyboards/fi.lproj/SettingsViews.strings
- xdrip/Storyboards/fr.lproj/SettingsViews.strings
- xdrip/Storyboards/it.lproj/SettingsViews.strings
- xdrip/Storyboards/nl.lproj/SettingsViews.strings
- xdrip/Storyboards/pl-PL.lproj/SettingsViews.strings
- xdrip/Storyboards/pt.lproj/SettingsViews.strings
- xdrip/Storyboards/ru.lproj/SettingsViews.strings
- xdrip/Storyboards/sl.lproj/SettingsViews.strings
- xdrip/Storyboards/sv.lproj/SettingsViews.strings
- xdrip/Storyboards/uk.lproj/SettingsViews.strings
- xdrip/Storyboards/zh.lproj/SettingsViews.strings
- xdrip/Texts/TextsSettingsView.swift
- xdrip/Texts/TextsTreatmentsView.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewTreatmentsSettingsViewModel.swift
- xdrip/View Controllers/Treatments/TreatmentsInsertViewController.swift
- xdrip/View Controllers/Treatments/TreatmentsViewController.swift
- the different treatment types (insulin, carbs, BG checks) can be filtered if required to show/hide them in the treatment table
- if boluses are shown, an option to filter micro-boluses is also enabled.
- button icon images are set individually as filled/unfilled to more clearly show if they are selected
- .getTreatments call reduced from 100 days to 21 days to save overhead
- previous settings options to show micro-boluses in the treatments table (and associated translations) removed as no longer needed
- safety feature added to prevent future BGs being added/assigned @bjornoleh
> implement treatment filtering in list

- xdrip/BluetoothTransmitter/CGM/Dexcom/Generic/String+Dexcom.swift
Dexcom seemed to have sold so many G6s that they've finished the alphabet and rolled back to before 8G. I have a transmitter manufactured in July 2022 with ID 8Dxxxx.
This change just identifies transmitters after 8A as Firefly (instead of 8G as before).
> Update minimum G6 Firefly ID from 8G to 8A

- xdrip/Managers/Alerts/AlertManager.swift
Minor bug in string replacement during translation. Change order of string replacement as "hour" is included in "hours". This affects all language translations
e.g.
> Fix translation issue on AlertManager

- xdrip/Constants/ConstantsWatch.swift
- xdrip/Core Data/classes/BgReading+CoreDataClass.swift
- xdrip/Extensions/UserDefaults.swift
- xdrip/Managers/Watch/WatchManager.swift
- xdrip/Storyboards/en.lproj/SettingsViews.strings
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewAppleWatchSettingsViewModel.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewSpeakSettingsViewModel.swift
- calendar event visual indicator (#411)
- will change colour depending on BG value as per main chart objective values for (urgent high, high, low and urgent low)
- option added to show/hide visual indicator in Calendar Event settings
- small changes made to interval label texts
Co-Authored-By: Gary Dalley <4158482+gonkowonko@users.noreply.github.com>
> Calendar event visual indicator option

- xdrip/Extensions/UserDefaults.swift
- xdrip/Managers/Loop/LoopManager.swift
- xdrip/Storyboards/en.lproj/SettingsViews.strings
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewDevelopmentSettingsViewModel.swift
- option added to the developer settings to limit sharing BG array to just once every 5 minutes (should maybe move all Loop options to a separate section in the future)
- added as a Loop 3 has removed the check to only calculate Loop cycles every 5 minutes and with the 60 second CGM data from Libre 2 BLE, this causes loop cycles very often and maybe drain some pump batteries.
- note that this new option does not give 5 minute readings per se... it will give Loop the array of last readings (irrespective of if they were every 1 or 5 minutes) every 5 minutes. The user will still see readings every 60 seconds, but they will arrive in blocks every 5 minutes and trigger a Loop cycle.
> Add option to share to Loop just once every 5 minutes

- xdrip/Managers/NightScout/NightScoutUploadManager.swift
Nightscout upload "Sensor Started" inconsistent with Nightscout's sensorage.js plugin
Changing back to "Start" for [Nightscout's sensorage.js plugin](https://github.com/nightscout/cgm-remote-monitor/blob/a09e586b95065d502390475bb4ec415f95c7eff5/lib/plugins/sensorage.js#L53) to work as previously.
> "Sensor Started" breaks Nightscout's plugin

- xdrip/BluetoothTransmitter/CGM/Dexcom/Generic/String+Dexcom.swift
Dexcom have now started reusing 80xxxx, 81xxxx (and also 82xxxx etc) for current transmitters.
I think there is almost nobody using old 80/81 transmitters in raw mode so let's just assure future compatibility in native mode for all G6 transmitters.
A future job should be to detect raw capability on each individual transmitter and enable raw mode if required (such as with Anubis transmitters).
> Treat all G6 transmitters (8xxxxx) as Firefly type

- xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreDataParser.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorSerialNumber.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorType.swift
EU L2 sensors have started appearing * with a new patchInfo configuration starting with c5 instead of the usual/previous 9d.
This commit enables support for these as a new sensor type allowing the serial number to be correctly reported as "3MHxxxxxxx" so that it will connect via BLE.
* these new c5 sensors have first appeared in Portugal in mid May 2023 but have now also started appearing in Germany.
> New L2 EU patchInfo designation "c5"

- xdrip.xcodeproj/project.pbxproj
- xdrip/Storyboards/en.lproj/SettingsViews.strings
- xdrip/Storyboards/es.lproj/BluetoothPeripheralView.strings
- xdrip/Storyboards/es.lproj/SettingsViews.strings
- xdrip/Storyboards/nl.lproj/SettingsViews.strings
- xdrip/Supporting Files/Info.plist
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewAppleWatchSettingsViewModel.swift
iOS17-specific NSCalendarsFullAccessUsageDescription key added to info.plist. This will allow the app to ask for Full Access when using iOS17.
If using iOS17, we will now check to see if Full Access is granted (if an existing user has just updated to iOS17, then it won't be). If not, then calendar events will be disabled (to prevent the calendar from filling up with old events) and we will prompt the user to update their calendar settings from 'Add Events Only' to 'Full Access'. If no access is granted, the existing warning is used.
Once the update to Full Access in the iPhone Settings, the app will allow normal Calendar Event use again.
if using <=iOS16 we will use the previous/existing workflow but with small corrections to the error messaging if calendar permission is disabled. …
> update project to work with new iOS17 EKEventStore requirements

- .github/workflows/build_xdrip.yml
- fastlane/testflight.md
A set of changes that brings the workflows in line with their origins in LoopKit/LoopWorkspace
One of the changes is that in the event of no repository activity, empty commits are no longer added to the master branch, but instead to a branch called 'alive', which is created automatically.
Checks for updates also happens less frequently, and now checks for updates at 08:00 UTC every Wednesday instead of on a daily basis.
Some of the recently reported build issues should hopefully be eliminated too.
Instructions in fastlans/testflight.md are updated, including removal of instructions for identifier 'Watch App WatchKit Extension'.
> Harmonise with Loop workflows

- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewAppleWatchSettingsViewModel.swift
This PR implements compiler switching to ensure that anything below Xcode 15 does not try and compile the new iOS17 Eventkit methods.
Tested on both Xcode 14 and Xcode 15 with success.
> Xcode14 fix

- .github/workflows/add_identifiers.yml
- .github/workflows/build_xdrip.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
Adding a step to workflow jobs that interface Apple servers, as a workaround for build issues caused by runner clocks being out of sync. See https://github.com/actions/runner issue number 2996 for details.
name: Sync clock
run: sudo sntp -sS time.windows.com
Added to the following workflows / jobs:
validate_secrets.yml / validate-fastlane-secrets
add_identifiers.yml / identifiers
build_xdrip.yml / build
create_certs.yml / certificates
> Sync the GitHub runner clock with the Windows time server

- xdrip/BluetoothTransmitter/CGM/Generic/CGMTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Generic/TransmitterBatteryInfo.swift
- xdrip/Constants/ConstantsDefaultAlertLevels.swift
- xdrip/Managers/Alerts/AlertKind.swift
Also change default alarm threshold to 260 (2600mV)
> Use VoltageB instead of VoltageA for Dexcom Transmitter Battery Alarms

- .github/workflows/add_identifiers.yml
- .github/workflows/build_xdrip.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
This PR fixes the warning users currently see for browser build for node v16, i.e.
```md
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
In accordance with [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), all actions must be using node version 20. Bumping the node version from v16 to v20 by using `aormsby/Fork-Sync-With-Upstream-action@v3.4.1` (latest release see [here](https://github.com/aormsby/Fork-Sync-With-Upstream-action/releases/tag/v3.4.1)) and `actions/checkout@v4` (which internally [updated …
> Bump node version for github action workflows

- xdrip/View Controllers/Root View Controller/RootViewController.swift
Live Activities have maximum payload size of 4kB.
At least Libre 2 EU produces so many values over 12 hours (some 400 readings for me) that they cannot be pushed to Live Activity unfiltered, causing Live Activity start to fail with error: `Payload maximum size exceeded`.
Fix by downsampling (just pick every nth reading) to maximum of 100 readings. 
The threshold value is got by trial and error, then tuning it down a bit to leave some room for different length strings.
> Fix `Payload maximum size exceeded` error when starting Live Activity

- xdrip/View Controllers/Root View Controller/RootViewController.swift
Reverts JohanDegraeve/xdripswift#513
The down sampling looks "wrong"...#513 
We need to check properly before re-merging.
> Revert "Fix `Payload maximum size exceeded` error when starting Live Activity"

- xDrip Widget/DataModels/XDripWidgetAttributes.swift
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- change private property naming to match conventions
- change the computed properties to be Swift computed properties and not stored in init
- lower the target number of readings for downsampling
I don't know why, but the 275 that was yesterday fine, was today morning too much. I need to use this a while on my device before I trust the value is low enough to not to fail.
> Live Activity downsampling: improvements

- xDrip Watch App/Views/MainView.swift
- xDrip Watch App/Views/SubViews/HeaderView.swift
- xDrip Widget/DataModels/XDripWidgetAttributes.swift
- xdrip.xcworkspace/xcshareddata/swiftpm/Package.resolved
- xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralCategory.swift
- xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralType.swift
- xdrip/Constants/ConstantsGlucoseChartSwiftUI.swift
- xdrip/Constants/ConstantsNightScout.swift
- xdrip/Extensions/UserDefaults.swift
- xdrip/Managers/Alerts/AlertManager.swift
- xdrip/Managers/LibreLinkUp/LibreLinkUpFollowManager.swift
- xdrip/Managers/Loop/LoopManager.swift
- xdrip/Managers/NightScout/NightScoutFollowManager.swift
- xdrip/Managers/NightScout/NightScoutUploadManager.swift
- xdrip/Texts/TextsSettingsView.swift
- xdrip/View Controllers/BluetoothPeripheralsNavigationController/BluetoothPeripheralsViewController/BluetoothPeripheralViewController/BluetoothPeripheralViewController.swift
- xdrip/View Controllers/BluetoothPeripheralsNavigationController/BluetoothPeripheralsViewController/BluetoothPeripheralViewController/Models/HeartBeat/Libre3HeartBeatBluetoothPeripheralViewModel.swift
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- xdrip/View Controllers/Treatments/TreatmentsInsertViewController.swift
- xdrip/View Controllers/Treatments/TreatmentsViewController.swift
- watch app/complications should now correctly scale for 40mm watches (https://www.facebook.com/groups/853994615056838/posts/1884748995314723/)
- changes to the way we write to userdefaults when performing NightscoutSyncRequired to try and minimise crashes due to memory access exceptions. This was especially noticeable when background keep-alive was enabled and new downloads were scheduled
- "Libre 3 Heartbeat" descriptions changed to show "Libre Heartbeat" (no internal changes)
- instructions are now added to the heartbeat screen, specific for the type of heartbeat being added
- changes to live activities to limit payload size to <4Kb and prevent issues for Libre 2 Direct users. (@stami)
- various small bug fixes
> 5.1.4 staging

- xdrip/Constants/ConstantsGlucoseChartSwiftUI.swift
- xdrip/Managers/Charts/GlucoseChartType.swift
- the previous/default black background wouldn't render correctly on Watchfaces that had a colour scheme applied.
Now rendering correctly with color scheme:
And also with the standard multicolor scheme:
Also renders correctly with the Modular Ultra face in Night mode:
> update background color for Watch accessoryRegular complication

- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFC.swift
- xdrip/Constants/ConstantsLibreLinkUp.swift
- xdrip/Extensions/String.swift
- xdrip/Managers/LibreLinkUp/LibreLinkUpFollowManager.swift
- xdrip/Managers/LibreLinkUp/LibreLinkUpModels.swift
With the beta of Xcode 16 compilation fails by reporting the error “The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions.” regarding the line
https://github.com/JohanDegraeve/xdripswift/blob/fec1005899893ddf20e36675f3aad96547e8c99c/xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFC.swift#L462
Simply replacing the final  `+  (error?.localizedDescription ?? "none”)` with `+ error.debugDescription` makes xDrip compilable again.
It was reported as successful on FB:
> Workaround for Xcode 16; new LLU `la` subdomain and 4.11 Account-Id header

- xDrip Watch App/DataModels/WatchStateModel.swift
- xDrip Watch Complication/XDripWatchComplication+Entry.swift
- xDrip Widget/DataModels/XDripWidgetAttributes.swift
- xDrip Widget/XDripWidget+Entry.swift
- xdrip/Core Data/classes/BgReading+CoreDataClass.swift
- Address issue #544 
- BUG FIX: xDrip incorrectly reported +0 (or 0.0 for mmol) BG deltas when delta was not actually 0 (or 0.0 for mmol) - this only occurred occasionally when BG deltas were around 1
- This fixes this issue, tested and verified on live device for mgdl
> Bug fix for false +0 (or +0.0 mmol) bg deltas

- xdrip/Constants/ConstantsUI.swift
- xdrip/Storyboards/Base.lproj/Main.storyboard
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- add dimming overlay support to the "landscape when screen is locked and rotated" view
- fix value label font size increase/decrease
- add empty view to hstack of main chart to maintain leading-edge spacing
- correctly show/hide pump and AID info views when locking/unlocking screen
> landscape big number view - dimming overlay

- xDrip/SwiftUIViews/AIDStatusView.swift
- xdrip/Managers/Nightscout/NightscoutProfileModels.swift
- xdrip/Managers/Nightscout/NightscoutSyncManager.swift
- Loop seems to store some values in the Nightscout profile as the wrong type (strings instead of Int). They're not needed anyway so just ignore/remove them from the data model
- add check to AIDStatusView to show an error message if the profile data is not available
- add token handling to the authentication for profile and deviceStatus fetching
> correction to profile download from Loop

- xdrip.xcodeproj/project.pbxproj
- xdrip/Managers/Followers/FollowerDataSourceType.swift
- xdrip/Managers/LibreLinkUp/LibreLinkUpFollowManager.swift
- xdrip/Managers/LibreLinkUp/LibreLinkUpModels.swift
- xdrip/Texts/TextsHomeView.swift
- xdrip/View Controllers/Root View Controller/RootViewController.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewDataSourceSettingsViewModel.swift
Allows access to the libreview.ru domains.
Is kept as a separate data source as there is no way to detect that RU should be used - no redirects are sent for different regions when trying to access the global URLS, the credentials are just rejected. Adding it as a separate data source makes things much cleaner.
Tested and working.
> add LLU Russia as new follower data source

- .github/workflows/add_identifiers.yml
- .github/workflows/build_xdrip.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
On April 24, we will no longer be able to do browser builds with Xcode 15:
> ITMS-90725: SDK version issue - This app was built with the iOS 17.5 SDK. Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution
This PR will take care of this by bumping to macos-15 and Xcode 16.2. This has already been used for some time in Loop Follow etc, and is well tested. The same PR has also been made to Trio.
All of the four workflows that run on macos runners are updated here.
> Use macos-15 and Xcode 16.2 in workflows

- .github/workflows/build_xdrip.yml
The gautamkrishnar/keepalive-workflow has been taken down by GitHub, and GitHub Actions builds are failing due to this. 
Disabling the keepalive-workflow because the repo is no longer available. A permanent fix will need to be implemented later, this is a bandaid to prevent all build workflows to fail.
Successful test of the workflow (the run was terminated manually after the critical steps had completed):
https://github.com/bjornoleh/xdripswift/actions/runs/14604108694
This is also the same change that was made for LoopWorkspace: LoopKit/LoopWorkspace#248, and a similar PR is being reviewed for Trio.
> build_xdrip.yml: Disable keepalive action

- xdrip/Constants/ConstantsDefaultAlertLevels.swift
- xdrip/Constants/ConstantsNotifications.swift
- xdrip/Managers/Alerts/AlertKind.swift
- xdrip/Managers/Alerts/AlertManager.swift
- xdrip/Texts/TextsAlerts.swift
I recently had a situation where I fell asleep at night and forgot to charge my phone. As a result, it ran out of battery, and I had no glucose readings for several hours, so Trio couldn’t loop. Luckily, nothing happened, but it made me realize that a low battery alert for the phone — not just the Dexcom transmitter — would make sense. That’s the background for this PR. I’ve been testing it live on my phone for a week now, and it’s been working well for me. If there’s interest in adding this to xDrip in general, here’s the PR 😄 
*for the second picture I set the alert treshold to 90 just to demonstrate the alert
> Low battery alert for phone

- xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Libre2/CGMLibre2Transmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreDataParser.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFC.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFCDelegate.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorSerialNumber.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorType.swift
- xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift
- Included detection for the new sensor type via patchInfo starting with "7F".
- Updated expected Bluetooth device name logic: now matches using the MAC address instead of "ABBOTT" + serial number.
- Successfully tested on a Libre 2 Plus EU sensor.
- Verified Bluetooth connection and continuous data reception.
> Handle new Libre 2 Plus EU (May 2025) sensors

- xdrip/BluetoothTransmitter/CGM/Libre/Atom/CGMAtomTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Libre2/CGMLibre2Transmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/MiaoMiao/CGMMiaoMiaoTransmitter.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFC.swift
- xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorType.swift
This pull request updates several instances where .bytes was used on String, Data, or [UInt8] values. These were relying on non-standard extensions or legacy behaviors that are no longer supported in recent versions of Swift (as used in Xcode on M4 Macs and newer toolchains). This issue also seems to affect VM installations using Xcode 15.5.
Example screenshot with compiler errors:
> corrections for type errors in newer m4 Macs

- xDrip Widget/Views/LiveActivityView.swift
- xDrip Widget/Views/LiveActivityViewContent.swift
- xDrip Widget/Views/LiveActivityViewContentActivityFamilies.swift
- xDrip Widget/XDripWidgetLiveActivity.swift
- xdrip.xcodeproj/project.pbxproj
- xdrip/SwiftUIViews/GlucoseChartView.swift
PR to correct widget backgrounds for when used with clear/tinted widget views. It also allows the live activity to show correct transparency with iOS26 liquid metal (also works nicely now for the widgets in iOS26 CarPlay).
Adds Smart Stack support to show the iOS Live Activity on the Apple Watch, together with CarPlay (iOS26).
> iOS26 updates

- xdrip/Supporting Files/Info.plist
In this patch, I enable UI file sharing using MacOS to allow you to backup / restore your database file.
I ran into an issue with the expiring public Testflight where to install with a new app identifier, it didn't pull the data from the old version.  This was an issue as I didn't want to lose months of CGM data.
I figure it would also be useful if anyone wants to muck around with the sqlite database themselves.
FYI for anyone running into the specific (expiring build) issue I did: 
1. Use Finder to create a full local backup
2. Use (iMazing)[http://imazing.com/] to extract the sqlite file
> (Backups -> click on your recent backup -> More -> File System -> Apps -> AppDomain.com.OLD_TESTFLIGHT_TEAM_ID.xdriftswift -> Documents), then download the sqlite file to your desktop.
3. Install your …
> Add support for UI file sharing to allow for database access / backup

- .github/workflows/build_xdrip.yml
Xcode 16.2 is no longer available on GitHub Actions and causes build errors.
This PR updates the workflow to use Xcode 16.4 instead.
Link to successful build: https://github.com/bjorkert/xdripswift/actions/runs/17187187012
> Update GitHub Actions to Xcode 16.4

- xDrip Widget/XDripWidgetLiveActivity.swift
- xdrip/Application Delegate/AppDelegate.swift
- xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewNightscoutSettingsViewModel.swift
Crash/Exception for one user with iOS26 Beta:
The fix is confirmed as working.
> Live Activity widget URL change + App Delegate handler + NS token auth
