JohanDegraeve/xdripswift

xdrip/Storyboards/Base.lproj/Main.storyboard
xdrip/Supporting Files/Info.plist

Johan - give this a try and see if it fixes the UI errors caused by releasing through Testflight.

NavBar changes to fix Titles

---

xdrip/Storyboards/fi.lproj/AlertTypesSettingsView.strings
xdrip/Storyboards/fi.lproj/HomeView.strings
xdrip/Storyboards/fi.lproj/LibreNFC.strings
xdrip/Storyboards/fi.lproj/LibreStates.strings
xdrip/Storyboards/fi.lproj/Main.strings
xdrip/Storyboards/fi.lproj/SettingsViews.strings

Unfortunately this is tested only in simulator

Added missing Finnish translations

---

xdrip/Constants/ConstantsStatistics.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

Final (non-critical) logic correction. Ready for production release.

---

xdrip/Storyboards/de.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/en.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/es.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/fr.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/nl.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/sv.lproj/BluetoothPeripheralView.strings
xdrip/Texts/TextsBluetoothPeripheralView.swift
xdrip/View Controllers/BluetoothPeripheralsNavigationController/BluetoothPeripheralsViewController/BluetoothPeripheralViewController/BluetoothPeripheralViewController.swift

#239 
Functionality tested and confirmed as working correctly by @liroyvh

Disconnect confirm

---

xdrip/Storyboards/de.lproj/BluetoothPeripheralView.strings
xdrip/Storyboards/de.lproj/BluetoothPeripheralsView.strings
xdrip/Storyboards/de.lproj/DexcomShareTestResult.strings
xdrip/Storyboards/de.lproj/HomeView.strings
xdrip/Storyboards/de.lproj/LibreNFC.strings
xdrip/Storyboards/de.lproj/M5StackView.strings
xdrip/Storyboards/de.lproj/NightScoutTestResult.strings
xdrip/Storyboards/de.lproj/SettingsViews.strings

Hi,
i fixed a few small translation and spelling Bugs for the german UI.
wishes
mg

German Translation - Spelling & Typos

---

xdrip/Storyboards/de.lproj/BluetoothPeripheralView.strings

Hi,
on last typo i've found.
wishes
mg

On last typo: scannnen --> scannen

---

xdrip/View Controllers/Root View Controller/RootViewController.swift

easter-egg-update

---

xdrip.xcodeproj/project.pbxproj
xdrip/Storyboards/Base.lproj/Main.storyboard
xdrip/Treatments/DateOnly.swift
xdrip/Treatments/TreatmentCollection.swift
xdrip/View Controllers/Treatments/TreatmentTableViewCell.swift
xdrip/View Controllers/Treatments/TreatmentsViewController.swift

Created TreatmentCollection, data structure that abstracts grouping treatments by date.
Treatments table view now uses sections.

Treatment table view now uses sections.

---

xdrip/View Controllers/Treatments/TreatmentsInsertViewController.swift

Treatments are only created if their value is greater than zero. This fixes 0 g of carbs, 0 U of insulin and 0 min of exercise being valid values.

Fixes being able to insert 0 carbs / insulin / exercise as a valid treatment.

---

xdrip/Storyboards/Base.lproj/Main.storyboard
xdrip/View Controllers/Treatments/TreatmentsInsertViewController.swift
xdrip/View Controllers/Treatments/TreatmentsViewController.swift

Treatments buttons moved to the top of the screen.

Treatments buttons are now at the top of the screen.

---

xdrip/Storyboards/Base.lproj/Main.storyboard

Fixed treatments table clipping due to autolayout constants.

Fixed treatments table clipping due to autolayout constants.

---

xdrip/Managers/NightScout/NightScoutUploadManager.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewNightScoutSettingsViewModel.swift

ns url unwrapping removed

---

xdrip/Managers/Charts/GlucoseChartManager.swift

Optimized getTreatmentEntryChartPoints to run faster.
- Previously, getTreatmentEntryChartPoints was generating lag and spikes of CPU usage.
- The code was optimized by reducing the amount of calls to getBgReadings.
- Now getBgReadings is only called once inside getTreatmentEntryChartPoints.
- Now calculateClosestYAxisValues interpolates the SGV value from the two closest bgReadings, if there are. 
- Profiling registered a speed up greater than 500%.

Optimized GlucoseChartManager getTreatmentEntryChartPoints.

---

xdrip.xcodeproj/project.pbxproj

Try to fix broken reference to BgReadingsDetailView.swift in project.pbxproj

Fix broken reference to BgReadingsDetailView.swift

---

Watch App WatchKit Extension/ExtensionDelegate.swift
xdrip.xcodeproj/project.pbxproj
xdrip.xcodeproj/xcshareddata/xcschemes/Watch App (Complication).xcscheme
xdrip.xcodeproj/xcshareddata/xcschemes/Watch App.xcscheme
xdrip.xcodeproj/xcshareddata/xcschemes/xDrip4iOS Widget.xcscheme
xdrip.xcodeproj/xcshareddata/xcschemes/xdrip.xcscheme
xdrip/Storyboards/Base.lproj/Main.storyboard
xdrip/View Controllers/Root View Controller/RootViewController.swift

fixes all of the compiler errors caused by dynamic font types etc in IB

fix compiler errors and sensor countdown bug

---

xdrip/Managers/Alerts/AlertManager.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

fix alarms for Nightscout follower mode

---

xdrip/Managers/LibreLinkUp/LibreLinkUpFollowManager.swift
xdrip/Managers/LibreLinkUp/LibreLinkUpModels.swift
xdrip/Managers/NightScout/NightScoutFollowManager.swift
xdrip/Utilities/Trace.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

- include all user settings and also extra transmitter information if available
- change layout to mimic actual settings screen
- simplify dates/times to make more readable

Various changes

---

xdrip/Storyboards/ru.lproj/Common.strings

Correct the word - "В диапазоне"

Update Common.strings  - "В диапазоне"

---

xDrip Widget/DataModels/XDripWidgetAttributes.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

Another take on #513 
See the discussion there.

downsample data if needed before sending it to live activity

---

xDrip Widget/Views/SystemLargeView.swift
xDrip Widget/Views/SystemMediumView.swift
xDrip Widget/Views/SystemSmallView.swift
xDrip Widget/XDripWidget+Entry.swift
xDrip Widget/XDripWidget+Provider.swift
xdrip/Managers/Followers/FollowerBackgroundKeepAliveType.swift
xdrip/Managers/Widgets/WidgetSharedUserDefaultsModel.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

Note, only for iOS widgets. Not the Live Activity or WatchOS widgets.

add keep alive icon to iOS widgets for follower modes

---

xdrip.xcodeproj/project.pbxproj

the changes that I missed to stage when committing before the original PR was merged

contact trick - missed file

---

xdrip.xcodeproj/project.pbxproj
xdrip/AppShortcuts.swift
xdrip/GlucoseIntent.swift
xdrip/GlucoseIntentResponseView.swift
xdrip/Supporting Files/Info.plist
xdrip/View Controllers/Helpers/SettingsViewModelProtocol.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewController.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewModels/SettingsViewInfoViewModel.swift

https://github.com/JohanDegraeve/xdripswift/pull/492

Siri integration merge from @gshaviv #492

---

xDrip Watch Complication/Texts/es.lproj/WatchComplication.strings
xDrip Watch Complication/Views/AccessoryRectangularView.swift
xDrip Watch Complication/XDripWatchComplication+Entry.swift
xdrip.xcodeproj/xcshareddata/xcschemes/xdrip.xcscheme

- this option was causing issues to automatically install the xDrip Widget Extension via Xcode when building the main xDrip target.

disabled Address Sanitizer in xDrip Run Scheme

---

xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreDataParser.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorSerialNumber.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorType.swift

- maxSensorDays set at 15.0 days for now until we get confirmation if we can still read an extra 12 hours as per other Libre sensors.

Libre 2+ EU implementation

---

xdrip/GlucoseIntent.swift
xdrip/Managers/ContactImage/ContactImageManager.swift

- Siri intent description updated to remove the word "Siri"
- Contact image crash fixed when there is no BG data in coredata

5.2.3 hotfix

---

xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralType.swift
xdrip/BluetoothTransmitter/CGM/Dexcom/G7/CGMG7Transmitter.swift
xdrip/Managers/BluetoothPeripheral/BluetoothPeripheralManager.swift
xdrip/Storyboards/ar.lproj/HomeView.strings
xdrip/Storyboards/da.lproj/HomeView.strings
xdrip/Storyboards/el.lproj/HomeView.strings
xdrip/Storyboards/en.lproj/HomeView.strings
xdrip/Storyboards/fi.lproj/HomeView.strings
xdrip/Storyboards/it.lproj/HomeView.strings
xdrip/Storyboards/pl-PL.lproj/HomeView.strings
xdrip/Storyboards/ru.lproj/HomeView.strings
xdrip/Storyboards/sl.lproj/HomeView.strings
xdrip/Storyboards/tr.lproj/HomeView.strings
xdrip/Storyboards/uk.lproj/HomeView.strings
xdrip/Storyboards/zh.lproj/HomeView.strings
xdrip/SwiftUIViews/BgReadingsDetailView.swift
xdrip/Texts/TextsHomeView.swift

- force enable webOOP always to force transmitter algorithm even if previously disabled

remove webOOP function completely for G7/ONE+ CGMTransmitter

---

xdrip/BluetoothPeripheral/Generic/BluetoothPeripheralType.swift
xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift

1.Added Bubble Nano support
2.Update Bubble/Bubble Mini/Bubble Nano appId

Added Bubble Nano support

---

xdrip/Storyboards/sv.lproj/BluetoothPeripheralView.strings

translations of messages:
- sv

Staging 5.4.0

---

xdrip/BluetoothTransmitter/CGM/Dexcom/G7/CGMG7Transmitter.swift
xdrip/BluetoothTransmitter/CGM/Generic/CGMTransmitter.swift
xdrip/Managers/ContactImage/ContactImageManager.swift
xdrip/Utilities/Trace.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift
xdrip/View Controllers/Treatments/TreatmentTableViewCell.swift

Release 5.4.2
Stelo improvements + minor logging changes

5.4.2 hotfix

---

xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift

Add Low Power Mode Command for Bubble Nano which implemented in firmware 8.1 and higher.

Add Low Power Mode Command for Bubble Nano which implemented in firmware 8.1 and higher.

---

xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift

Confirmed as working and seems to fix the Nano disconnect issue previously reported in Facebook.

Bubble nano updates

---

xdrip/Managers/Nightscout/NightscoutSyncManager.swift

was "incorrectly optimised" by Paul here:
https://github.com/JohanDegraeve/xdripswift/commit/83c8a2afa67d440484cf293265a070da2f53f2b1

fix: correctly add query items for http DELETE request

---

fastlane/testflight.md

Add instructions for adding "Trio App Group"

---

xdrip.xcodeproj/project.pbxproj
xdrip/Constants/ConstantsPickerView.swift
xdrip/Managers/Alerts/AlertManager.swift
xdrip/Storyboards/en.lproj/Common.strings
xdrip/Storyboards/es.lproj/Common.strings
xdrip/Texts/TextsCommon.swift
xdrip/View Controllers/BluetoothPeripheralsNavigationController/BluetoothPeripheralsViewController/BluetoothPeripheralsViewController.swift
xdrip/View Controllers/Helpers/Date Picker View Controller/DatePickerViewControllerModal.swift
xdrip/View Controllers/Helpers/Date Picker View Controller/DatePickerViewData.swift
xdrip/View Controllers/Helpers/Picker View Controller/PickerViewControllerModal.swift
xdrip/View Controllers/Helpers/Picker View Controller/PickerViewData.swift
xdrip/View Controllers/Root View Controller/SnoozeViewController.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/AlertTypesSettingsViewController/AlertTypeSettingsViewController/AlertTypeSettingsViewController.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/AlertsSettingsViewController/AlertSettingsViewController/AlertSettingsViewControllerData.swift
xdrip/View Controllers/SettingsNavigationController/SettingsViewController/SettingsViewUtilities.swift

- Will adjust modal view controller height if a main title or/and subtitle is not used. 
- Modal view will cancel and dismiss if swiped down beyond a certain point.
- isFullScreen attribute added to pickerViewData/datePickerViewData to make the view height smaller when displayed over a full screen view (such as snooze view) where a navigation controller is not shown.
- written to act as a direct, drop-in replacement for the previous picker / datePicker view controllers with all presentation/dismissing taking place inside the vc class.
PickerViewControllerModal:
DatePickerViewControllerModal:

modal picker views (list/date)

---

xdrip/View Controllers/Helpers/Date Picker View Controller/DatePickerViewControllerModal.swift
xdrip/View Controllers/Helpers/Picker View Controller/PickerViewControllerModal.swift
xdrip/View Controllers/Root View Controller/RootViewController.swift

also set minuteInterval to 10 when using the date picker in time only mode.

modal picker views tidy up + use also for alarm snooze

---

xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift
xdrip/BluetoothTransmitter/CGM/Libre/Libre2/CGMLibre2Transmitter.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreDataParser.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFC.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreNFCDelegate.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorSerialNumber.swift
xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorType.swift
xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift
xdrip/Managers/LibreLinkUp/LibreLinkUpFollowManager.swift

Libre 2 Plus EU (7f) Implementation

---

fastlane/testflight.md

The fastlane/testflight.md file was out of date.
* Bring over some text and link updates to xdripswift from other OS AID apps.
* Update the list of Identifiers which require the configuration of App Groups
* Add the detailed table for Identifiers
* Update information about annual certificate renewal

update instructions, update the Identifier list
